language: node_js
node_js: "8"
stages: 
    - name: unit_tests
    - name: documentation
      if: branch = DEV
    
jobs:
    include:
        - stage: unit_tests
          env: CHECK = UNIT_TESTS
          script: 
            - "npm install"
            - "npm run test"
        - stage: documentation
          script: 'echo "running documentation"'
